image: ruby

pages:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
